/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OracleDaily } from "./OracleDaily";

export { OracleDaily__factory } from "./factories/OracleDaily__factory";
