/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { OracleDaily } from "./OracleDaily";

export { Ownable__factory } from "./factories/Ownable__factory";
export { OracleDaily__factory } from "./factories/OracleDaily__factory";
